export const get_driverOptionalList_success = 'get_driverOptionalList_success'
export const get_driverOptionalList_failed = 'get_driverOptionalList_failed'
export const get_driverOptionalList_error = 'get_driverOptionalList_error'
export const get_driverOptionalList_waiting = 'get_driverOptionalList_waiting'