export const upload_imageForCreateAccident_success = 'upload_imageForCreateAccident_success'
export const upload_imageForCreateAccident_partSuccess = 'upload_imageForCreateAccident_partSuccess'
export const upload_imageForCreateAccident_failed = 'upload_imageForCreateAccident_failed'
export const upload_imageForCreateAccident_error = 'upload_imageForCreateAccident_error'
export const upload_imageForCreateAccident_waiting = 'upload_imageForCreateAccident_waiting'
export const clean_imageForCreateAccident = 'clean_imageForCreateAccident'

export const del_imageForCreateAccident_success = 'del_imageForCreateAccident_success'
export const del_imageForCreateAccident_failed = 'del_imageForCreateAccident_failed'
export const del_imageForCreateAccident_error = 'del_imageForCreateAccident_error'
export const del_imageForCreateAccident_waiting = 'del_imageForCreateAccident_waiting'

export const set_indexForUploadImageForCreateAccident = 'set_indexForUploadImageForCreateAccident'


export const get_imageForCreateAccident_success = 'get_imageForCreateAccident_success'
export const get_imageForCreateAccident_failed = 'get_imageForCreateAccident_failed'
export const get_imageForCreateAccident_error = 'get_imageForCreateAccident_error'
export const get_imageForCreateAccident_waiting = 'get_imageForCreateAccident_waiting'
