export const CREATE_TruckFirst_SUCCESS = 'CREATE_TruckFirst_SUCCESS'
export const CREATE_TruckFirst_FAILED = 'CREATE_TruckFirst_FAILED'
export const CREATE_TruckFirst_WAITING = 'CREATE_TruckFirst_WAITING'
export const CREATE_TruckFirst_SERVICEERROR = 'CREATE_TruckFirst_SERVICEERROR'
export const CREATE_TruckFirst_ERROR = 'CREATE_TruckFirst_ERROR'
export const RESET_CREATE_TruckFirst = 'RESET_CREATE_TruckFirst'

export const CREATE_TruckTrailer_SUCCESS = 'CREATE_TruckTrailer_SUCCESS'
export const CREATE_TruckTrailer_FAILED = 'CREATE_TruckTrailer_FAILED'
export const CREATE_TruckTrailer_WAITING = 'CREATE_TruckTrailer_WAITING'
export const CREATE_TruckTrailer_SERVICEERROR = 'CREATE_TruckTrailer_SERVICEERROR'
export const CREATE_TruckTrailer_ERROR = 'CREATE_TruckTrailer_ERROR'
export const RESET_CREATE_TruckTrailer = 'RESET_CREATE_TruckTrailer'

export const CLEAN_AddTruckFirstReducer = 'CLEAN_AddTruckFirstReducer'