export const GET_DriverInfo_SUCCESS = 'GET_DriverInfo_SUCCESS'
export const GET_DriverInfo_FAILED = 'GET_DriverInfo_FAILED'
export const GET_DriverInfo_WAITING = 'GET_DriverInfo_WAITING'
export const GET_DriverInfo_SERVICEERROR = 'GET_DriverInfo_SERVICEERROR'
export const GET_DriverInfo_ERROR = 'GET_DriverInfo_ERROR'
export const RESET_GET_DriverInfo = 'RESET_GET_DriverInfo'

export const GET_DriverRecord_SUCCESS = 'GET_DriverRecord_SUCCESS'
export const GET_DriverRecord_FAILED = 'GET_DriverRecord_FAILED'
export const GET_DriverRecord_WAITING = 'GET_DriverRecord_WAITING'
export const GET_DriverRecord_SERVICEERROR = 'GET_DriverRecord_SERVICEERROR'
export const GET_DriverRecord_ERROR = 'GET_DriverRecord_ERROR'
export const RESET_GET_DriverRecord = 'RESET_GET_DriverRecord'

export const ChangeDriverStatus_SUCCESS = 'ChangeDriverStatus_SUCCESS'
export const ChangeDriverStatus_FAILED = 'ChangeDriverStatus_FAILED'
export const ChangeDriverStatus_WAITING = 'ChangeDriverStatus_WAITING'
export const ChangeDriverStatus_SERVICEERROR = 'ChangeDriverStatus_SERVICEERROR'
export const ChangeDriverStatus_ERROR = 'ChangeDriverStatus_ERROR'
export const RESET_ChangeDriverStatus = 'RESET_ChangeDriverStatus'

export const BindTruck_SUCCESS = 'BindTruck_SUCCESS'
export const BindTruck_FAILED = 'BindTruck_FAILED'
export const BindTruck_WAITING = 'BindTruck_WAITING'
export const BindTruck_SERVICEERROR = 'BindTruck_SERVICEERROR'
export const BindTruck_ERROR = 'BindTruck_ERROR'
export const RESET_BindTruck = 'RESET_BindTruck'

export const UnBindTruck_SUCCESS = 'UnBindTruck_SUCCESS'
export const UnBindTruck_FAILED = 'UnBindTruck_FAILED'
export const UnBindTruck_WAITING = 'UnBindTruck_WAITING'
export const UnBindTruck_SERVICEERROR = 'UnBindTruck_SERVICEERROR'
export const UnBindTruck_ERROR = 'UnBindTruck_ERROR'
export const RESET_UnBindTruck ='RESET_UnBindTruck'

export const CHANGE_DriverInfo_FIELD = 'CHANGE_DriverInfo_FIELD'

export const UPDATE_DriverInfoDrivingImage_SUCCESS = 'UPDATE_DriverInfoDrivingImage_SUCCESS'
export const UPDATE_DriverInfoDrivingImage_FAILED = 'UPDATE_DriverInfoDrivingImage_FAILED'
export const UPDATE_DriverInfoDrivingImage_WAITING = 'UPDATE_DriverInfoDrivingImage_WAITING'
export const UPDATE_DriverInfoDrivingImage_SERVICEERROR = 'UPDATE_DriverInfoDrivingImage_SERVICEERROR'
export const UPDATE_DriverInfoDrivingImage_ERROR = 'UPDATE_DriverInfoDrivingImage_ERROR'
export const RESET_UPDATE_DriverInfoDrivingImage = 'RESET_UPDATE_DriverInfoDrivingImage'

export const UPDATE_DriverInfoLicenseImage_SUCCESS = 'UPDATE_DriverInfoLicenseImage_SUCCESS'
export const UPDATE_DriverInfoLicenseImage_FAILED = 'UPDATE_DriverInfoLicenseImage_FAILED'
export const UPDATE_DriverInfoLicenseImage_WAITING = 'UPDATE_DriverInfoLicenseImage_WAITING'
export const UPDATE_DriverInfoLicenseImage_SERVICEERROR = 'UPDATE_DriverInfoLicenseImage_SERVICEERROR'
export const UPDATE_DriverInfoLicenseImage_ERROR = 'UPDATE_DriverInfoLicenseImage_ERROR'
export const RESET_UPDATE_DriverInfoLicenseImage = 'RESET_UPDATE_DriverInfoLicenseImage'