export const GET_OperateTypeCount_SUCCESS = Symbol('GET_OperateTypeCount_SUCCESS')
export const GET_OperateTypeCount_FAILED = Symbol('GET_OperateTypeCount_FAILED')
export const GET_OperateTypeCount_WAITING = Symbol('GET_OperateTypeCount_WAITING')
export const GET_OperateTypeCount_SERVICEERROR = Symbol('GET_OperateTypeCount_SERVICEERROR')
export const GET_OperateTypeCount_ERROR = Symbol('GET_OperateTypeCount_ERROR')
export const RESET_GET_OperateTypeCount = Symbol('RESET_GET_OperateTypeCount')

export const GET_WaitingInspectCount_SUCCESS = Symbol('GET_WaitingInspectCount_SUCCESS')
export const GET_WaitingInspectCount_FAILED = Symbol('GET_WaitingInspectCount_FAILED')
export const GET_WaitingInspectCount_WAITING = Symbol('GET_WaitingInspectCount_WAITING')
export const GET_WaitingInspectCount_SERVICEERROR = Symbol('GET_WaitingInspectCount_SERVICEERROR')
export const GET_WaitingInspectCount_ERROR = Symbol('GET_WaitingInspectCount_ERROR')
export const RESET_GET_WaitingInspectCount = Symbol('RESET_GET_WaitingInspectCount')

export const CLEAN_HomeReducer = Symbol('CLEAN_HomeReducer')