export const GET_InsuranceList_SUCCESS = 'GET_InsuranceList_SUCCESS'
export const GET_InsuranceList_FAILED = 'GET_InsuranceList_FAILED'
export const GET_InsuranceList_WAITING = 'GET_InsuranceList_WAITING'
export const GET_InsuranceList_SERVICEERROR = 'GET_InsuranceList_SERVICEERROR'
export const GET_InsuranceList_ERROR = 'GET_InsuranceList_ERROR'
export const RESET_GET_InsuranceList = 'RESET_GET_InsuranceList'