export const GET_MakeList_SUCCESS = Symbol('GET_MakeList_SUCCESS')
export const GET_MakeList_FAILED = Symbol('GET_MakeList_FAILED')
export const GET_MakeList_WAITING = Symbol('GET_MakeList_WAITING')
export const GET_MakeList_SERVICEERROR = Symbol('GET_MakeList_SERVICEERROR')
export const GET_MakeList_ERROR = Symbol('GET_MakeList_ERROR')