export const GET_TruckInfo_SUCCESS = 'GET_TruckInfo_SUCCESS'
export const GET_TruckInfo_FAILED = 'GET_TruckInfo_FAILED'
export const GET_TruckInfo_WAITING = 'GET_TruckInfo_WAITING'
export const GET_TruckInfo_SERVICEERROR = 'GET_TruckInfo_SERVICEERROR'
export const GET_TruckInfo_ERROR = 'GET_TruckInfo_ERROR'
export const RESET_GET_TruckInfo = 'RESET_GET_TruckInfo'

export const GET_TruckInsureRel_SUCCESS = 'GET_TruckInsureRel_SUCCESS'
export const GET_TruckInsureRel_FAILED = 'GET_TruckInsureRel_FAILED'
export const GET_TruckInsureRel_WAITING = 'GET_TruckInsureRel_WAITING'
export const GET_TruckInsureRel_SERVICEERROR = 'GET_TruckInsureRel_SERVICEERROR'
export const GET_TruckInsureRel_ERROR = 'GET_TruckInsureRel_ERROR'
export const RESET_GET_TruckInsureRel = 'RESET_GET_TruckInsureRel'

export const GET_TruckRecord_SUCCESS = 'GET_TruckRecord_SUCCESS'
export const GET_TruckRecord_FAILED = 'GET_TruckRecord_FAILED'
export const GET_TruckRecord_WAITING = 'GET_TruckRecord_WAITING'
export const GET_TruckRecord_SERVICEERROR = 'GET_TruckRecord_SERVICEERROR'
export const GET_TruckRecord_ERROR = 'GET_TruckRecord_ERROR'
export const RESET_GET_TruckRecord = 'RESET_GET_TruckRecord'

export const UpdateTruckInfo_SUCCESS = 'UpdateTruckInfo_SUCCESS'
export const UpdateTruckInfo_FAILED = 'UpdateTruckInfo_FAILED'
export const UpdateTruckInfo_WAITING = 'UpdateTruckInfo_WAITING'
export const UpdateTruckInfo_SERVICEERROR = 'UpdateTruckInfo_SERVICEERROR'
export const UpdateTruckInfo_ERROR = 'UpdateTruckInfo_ERROR'
export const RESET_UpdateTruckInfo = 'RESET_UpdateTruckInfo'

export const BindTrail_SUCCESS = 'BindTrail_SUCCESS'
export const BindTrail_FAILED = 'BindTrail_FAILED'
export const BindTrail_WAITING = 'BindTrail_WAITING'
export const BindTrail_SERVICEERROR = 'BindTrail_SERVICEERROR'
export const BindTrail_ERROR = 'BindTrail_ERROR'
export const RESET_BindTrail = 'RESET_BindTrail'

export const UnBindTrail_SUCCESS = 'UnBindTrail_SUCCESS'
export const UnBindTrail_FAILED = 'UnBindTrail_FAILED'
export const UnBindTrail_WAITING = 'UnBindTrail_WAITING'
export const UnBindTrail_SERVICEERROR = 'UnBindTrail_SERVICEERROR'
export const UnBindTrail_ERROR = 'UnBindTrail_ERROR'
export const RESET_UnBindTrail ='RESET_UnBindTrail'

export const BindDriver_SUCCESS = 'BindDriver_SUCCESS'
export const BindDriver_FAILED = 'BindDriver_FAILED'
export const BindDriver_WAITING = 'BindDriver_WAITING'
export const BindDriver_SERVICEERROR = 'BindDriver_SERVICEERROR'
export const BindDriver_ERROR = 'BindDriver_ERROR'
export const RESET_BindDriver = 'RESET_BindDriver'

export const UnBindDriver_SUCCESS = 'UnBindDriver_SUCCESS'
export const UnBindDriver_FAILED = 'UnBindDriver_FAILED'
export const UnBindDriver_WAITING = 'UnBindDriver_WAITING'
export const UnBindDriver_SERVICEERROR = 'UnBindDriver_SERVICEERROR'
export const UnBindDriver_ERROR = 'UnBindDriver_ERROR'
export const RESET_UnBindDriver = 'RESET_UnBindDriver'

export const UpdateTruckCredentialsImage_SUCCESS = 'UpdateTruckCredentialsImage_SUCCESS'
export const UpdateTruckCredentialsImage_FAILED = 'UpdateTruckCredentialsImage_FAILED'
export const UpdateTruckCredentialsImage_WAITING = 'UpdateTruckCredentialsImage_WAITING'
export const UpdateTruckCredentialsImage_SERVICEERROR = 'UpdateTruckCredentialsImage_SERVICEERROR'
export const UpdateTruckCredentialsImage_ERROR = 'UpdateTruckCredentialsImage_ERROR'
export const RESET_UpdateTruckCredentialsImage = 'RESET_UpdateTruckCredentialsImage'

export const CreateTruckImage_SUCCESS = 'CreateTruckImage_SUCCESS'
export const CreateTruckImage_FAILED = 'CreateTruckImage_FAILED'
export const CreateTruckImage_WAITING = 'CreateTruckImage_WAITING'
export const CreateTruckImage_SERVICEERROR = 'CreateTruckImage_SERVICEERROR'
export const CreateTruckImage_ERROR = 'CreateTruckImage_ERROR'
export const RESET_CreateTruckImage = 'RESET_CreateTruckImage'

export const DelTruckImage_SUCCESS = 'DelTruckImage_SUCCESS'
export const DelTruckImage_FAILED = 'DelTruckImage_FAILED'
export const DelTruckImage_WAITING = 'DelTruckImage_WAITING'
export const DelTruckImage_SERVICEERROR = 'DelTruckImage_SERVICEERROR'
export const DelTruckImage_ERROR = 'DelTruckImage_ERROR'
export const RESET_DelTruckImage = 'RESET_DelTruckImage'

export const ChangeTruckStatus_SUCCESS = 'ChangeTruckStatus_SUCCESS'
export const ChangeTruckStatus_FAILED = 'ChangeTruckStatus_FAILED'
export const ChangeTruckStatus_WAITING = 'ChangeTruckStatus_WAITING'
export const ChangeTruckStatus_SERVICEERROR = 'ChangeTruckStatus_SERVICEERROR'
export const ChangeTruckStatus_ERROR = 'ChangeTruckStatus_ERROR'
export const RESET_ChangeTruckStatus = 'RESET_ChangeTruckStatus'

export const CLEAN_TruckInfoReducer = 'CLEAN_TruckInfoReducer'


