export const GET_TruckInfo_SUCCESS = Symbol('GET_TruckInfo_SUCCESS')
export const GET_TruckInfo_FAILED = Symbol('GET_TruckInfo_FAILED')
export const GET_TruckInfo_WAITING = Symbol('GET_TruckInfo_WAITING')
export const GET_TruckInfo_SERVICEERROR = Symbol('GET_TruckInfo_SERVICEERROR')
export const GET_TruckInfo_ERROR = Symbol('GET_TruckInfo_ERROR')
export const RESET_GET_TruckInfo = Symbol('RESET_GET_TruckInfo')

export const GET_TruckInsureRel_SUCCESS = Symbol('GET_TruckInsureRel_SUCCESS')
export const GET_TruckInsureRel_FAILED = Symbol('GET_TruckInsureRel_FAILED')
export const GET_TruckInsureRel_WAITING = Symbol('GET_TruckInsureRel_WAITING')
export const GET_TruckInsureRel_SERVICEERROR = Symbol('GET_TruckInsureRel_SERVICEERROR')
export const GET_TruckInsureRel_ERROR = Symbol('GET_TruckInsureRel_ERROR')
export const RESET_GET_TruckInsureRel = Symbol('RESET_GET_TruckInsureRel')

export const GET_TruckRecord_SUCCESS = Symbol('GET_TruckRecord_SUCCESS')
export const GET_TruckRecord_FAILED = Symbol('GET_TruckRecord_FAILED')
export const GET_TruckRecord_WAITING = Symbol('GET_TruckRecord_WAITING')
export const GET_TruckRecord_SERVICEERROR = Symbol('GET_TruckRecord_SERVICEERROR')
export const GET_TruckRecord_ERROR = Symbol('GET_TruckRecord_ERROR')
export const RESET_GET_TruckRecord = Symbol('RESET_GET_TruckRecord')

export const UpdateTruckInfo_SUCCESS = Symbol('UpdateTruckInfo_SUCCESS')
export const UpdateTruckInfo_FAILED = Symbol('UpdateTruckInfo_FAILED')
export const UpdateTruckInfo_WAITING = Symbol('UpdateTruckInfo_WAITING')
export const UpdateTruckInfo_SERVICEERROR = Symbol('UpdateTruckInfo_SERVICEERROR')
export const UpdateTruckInfo_ERROR = Symbol('UpdateTruckInfo_ERROR')
export const RESET_UpdateTruckInfo = Symbol('RESET_UpdateTruckInfo')

export const BindTrail_SUCCESS = Symbol('BindTrail_SUCCESS')
export const BindTrail_FAILED = Symbol('BindTrail_FAILED')
export const BindTrail_WAITING = Symbol('BindTrail_WAITING')
export const BindTrail_SERVICEERROR = Symbol('BindTrail_SERVICEERROR')
export const BindTrail_ERROR = Symbol('BindTrail_ERROR')
export const RESET_BindTrail = Symbol('RESET_BindTrail')

export const UnBindTrail_SUCCESS = Symbol('UnBindTrail_SUCCESS')
export const UnBindTrail_FAILED = Symbol('UnBindTrail_FAILED')
export const UnBindTrail_WAITING = Symbol('UnBindTrail_WAITING')
export const UnBindTrail_SERVICEERROR = Symbol('UnBindTrail_SERVICEERROR')
export const UnBindTrail_ERROR = Symbol('UnBindTrail_ERROR')
export const RESET_UnBindTrail = Symbol('RESET_UnBindTrail')

export const BindDriver_SUCCESS = Symbol('BindDriver_SUCCESS')
export const BindDriver_FAILED = Symbol('BindDriver_FAILED')
export const BindDriver_WAITING = Symbol('BindDriver_WAITING')
export const BindDriver_SERVICEERROR = Symbol('BindDriver_SERVICEERROR')
export const BindDriver_ERROR = Symbol('BindDriver_ERROR')
export const RESET_BindDriver = Symbol('RESET_BindDriver')

export const UnBindDriver_SUCCESS = Symbol('UnBindDriver_SUCCESS')
export const UnBindDriver_FAILED = Symbol('UnBindDriver_FAILED')
export const UnBindDriver_WAITING = Symbol('UnBindDriver_WAITING')
export const UnBindDriver_SERVICEERROR = Symbol('UnBindDriver_SERVICEERROR')
export const UnBindDriver_ERROR = Symbol('UnBindDriver_ERROR')
export const RESET_UnBindDriver = Symbol('RESET_UnBindDriver')

export const UpdateTruckCredentialsImage_SUCCESS = Symbol('UpdateTruckCredentialsImage_SUCCESS')
export const UpdateTruckCredentialsImage_FAILED = Symbol('UpdateTruckCredentialsImage_FAILED')
export const UpdateTruckCredentialsImage_WAITING = Symbol('UpdateTruckCredentialsImage_WAITING')
export const UpdateTruckCredentialsImage_SERVICEERROR = Symbol('UpdateTruckCredentialsImage_SERVICEERROR')
export const UpdateTruckCredentialsImage_ERROR = Symbol('UpdateTruckCredentialsImage_ERROR')
export const RESET_UpdateTruckCredentialsImage = Symbol('RESET_UpdateTruckCredentialsImage')

export const CreateTruckImage_SUCCESS = Symbol('CreateTruckImage_SUCCESS')
export const CreateTruckImage_FAILED = Symbol('CreateTruckImage_FAILED')
export const CreateTruckImage_WAITING = Symbol('CreateTruckImage_WAITING')
export const CreateTruckImage_SERVICEERROR = Symbol('CreateTruckImage_SERVICEERROR')
export const CreateTruckImage_ERROR = Symbol('CreateTruckImage_ERROR')
export const RESET_CreateTruckImage = Symbol('RESET_CreateTruckImage')

export const DelTruckImage_SUCCESS = Symbol('DelTruckImage_SUCCESS')
export const DelTruckImage_FAILED = Symbol('DelTruckImage_FAILED')
export const DelTruckImage_WAITING = Symbol('DelTruckImage_WAITING')
export const DelTruckImage_SERVICEERROR = Symbol('DelTruckImage_SERVICEERROR')
export const DelTruckImage_ERROR = Symbol('DelTruckImage_ERROR')
export const RESET_DelTruckImage = Symbol('RESET_DelTruckImage')

export const ChangeTruckStatus_SUCCESS = Symbol('ChangeTruckStatus_SUCCESS')
export const ChangeTruckStatus_FAILED = Symbol('ChangeTruckStatus_FAILED')
export const ChangeTruckStatus_WAITING = Symbol('ChangeTruckStatus_WAITING')
export const ChangeTruckStatus_SERVICEERROR = Symbol('ChangeTruckStatus_SERVICEERROR')
export const ChangeTruckStatus_ERROR = Symbol('ChangeTruckStatus_ERROR')
export const RESET_ChangeTruckStatus = Symbol('RESET_ChangeTruckStatus')

export const CLEAN_TruckInfoReducer = Symbol('CLEAN_TruckInfoReducer')


