export const get_TruckHomeFilterList_success = 'get_TruckHomeFilterList_success'
export const get_TruckHomeFilterList_failed = 'get_TruckHomeFilterList_failed'
export const get_TruckHomeFilterList_waiting = 'get_TruckHomeFilterList_waiting'
export const get_TruckHomeFilterList_error = 'get_TruckHomeFilterList_error'

export const get_TruckHomeFilterListMore_success = 'get_TruckHomeFilterListMore_success'
export const get_TruckHomeFilterListMore_failed = 'get_TruckHomeFilterListMore_failed'
export const get_TruckHomeFilterListMore_waiting = 'get_TruckHomeFilterListMore_waiting'
export const get_TruckHomeFilterListMore_error = 'get_TruckHomeFilterListMore_error'
