export const modify_overuseDieselOil_success = 'modify_overuseDieselOil_success'
export const modify_overuseDieselOil_failed = 'modify_overuseDieselOil_failed'
export const modify_overuseDieselOil_error = 'modify_overuseDieselOil_error'
export const modify_overuseDieselOil_waiting = 'modify_overuseDieselOil_waiting'