export const create_accidentIndemnify_success = 'create_accidentIndemnify_success'
export const create_accidentIndemnify_failed = 'create_accidentIndemnify_failed'
export const create_accidentIndemnify_waiting = 'create_accidentIndemnify_waiting'
export const create_accidentIndemnify_error = 'create_accidentIndemnify_error'